language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
os:
  - linux
#  - osx
addons:
  apt:
    packages:
    - pypy
before_script:
  - pip install codecov
  - pip install coverage
  - curl https://bootstrap.pypa.io/get-pip.py > get-pip.py
  - pypy get-pip.py --user
  - pypy -m pip install --user coverage
  - export COVERAGE_PROCESS_START=$(pwd)/.coveragerc
  - echo $TRAVIS_PYTHON_VERSION && which python && which pypy && python -c 'import os, sys; print(os.path.basename(sys.executable))'
script:
  - coverage run setup.py test
after_success:
  - coverage combine .coverage.*
  - coverage report
  - codecov
