language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
os:
  - linux
#  - osx
addons:
  apt:
    packages:
    - pypy
before_install:
  - pip install codecov
  - pip install coverage
script:
  - echo $TRAVIS_PYTHON_VERSION && which python && which pypy
  - python -c 'import os, sys; print(os.path.basename(sys.executable))'
  - coverage run setup.py test
after_success:
  - coverage report
  - codecov
