language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
  - "3.5-dev" # 3.5 development branch
  - "3.6-dev" # 3.6 development branch
  - "nightly" # currently points to 3.7-dev
os:
  - linux
#  - osx
matrix:
  allow_failures:
  - python: "pypy3"
  - python: "3.5-dev"
  - python: "3.6-dev"
  - python: "nightly"
env:
  - PYTHONOPTIMIZE=''
  - PYTHONOPTIMIZE='YES'
addons:
  apt:
    packages:
    - pypy
before_script:
  - pip install codecov
  - pip install coverage
  - curl https://bootstrap.pypa.io/get-pip.py > get-pip.py
  - pypy get-pip.py || pypy get-pip.py --user
  - pypy -m pip install coverage || pypy -m pip install --user coverage
  - pypy -m pip install backports.range || pypy -m pip install --user backports.range
  - export COVERAGE_PROCESS_START=$(pwd)/.coveragerc
  - echo $TRAVIS_PYTHON_VERSION && which python && which pypy && python -c 'import os, sys; print(os.path.basename(sys.executable))'
script:
  - coverage run setup.py test
after_success:
  - coverage combine .coverage.*
  - coverage report
  - codecov
