language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
os:
  - linux
#  - osx
script:
  - echo $TRAVIS_PYTHON_VERSION
  - $TRAVIS_PYTHON_VERSION -m unittest discover -s cpy2py_unittests  -t '.'
