language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
os:
  - linux
#  - osx
addons:
  apt:
    packages:
    - pypy
script:
  - echo $TRAVIS_PYTHON_VERSION
  - which python
  - python -c 'import os, sys; print(os.path.basename(sys.executable))'
  - for file in $(ls cpy2py_unittests/test*.py); do python -m unittest cpy2py_unittests.$(basename ${file%.py}); done
